// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainsim.proto
// Protobuf Java Version: 4.29.3

package trainsim.proto;

public interface LTEDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trainsim.LTEData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>float signal_strength = 2;</code>
   * @return The signalStrength.
   */
  float getSignalStrength();

  /**
   * <code>float latency = 3;</code>
   * @return The latency.
   */
  float getLatency();

  /**
   * <code>float throughput = 4;</code>
   * @return The throughput.
   */
  float getThroughput();
}
