// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainsim.proto
// Protobuf Java Version: 4.29.3

package trainsim.proto;

/**
 * <pre>
 * *
 * Encapsulates the LTEData we want to collect from NS3 to send to MCAPL
 * </pre>
 *
 * Protobuf type {@code trainsim.LTEData}
 */
public final class LTEData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:trainsim.LTEData)
    LTEDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      LTEData.class.getName());
  }
  // Use LTEData.newBuilder() to construct.
  private LTEData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LTEData() {
    id_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return trainsim.proto.TrainSimProto.internal_static_trainsim_LTEData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return trainsim.proto.TrainSimProto.internal_static_trainsim_LTEData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            trainsim.proto.LTEData.class, trainsim.proto.LTEData.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNAL_STRENGTH_FIELD_NUMBER = 2;
  private float signalStrength_ = 0F;
  /**
   * <code>float signal_strength = 2;</code>
   * @return The signalStrength.
   */
  @java.lang.Override
  public float getSignalStrength() {
    return signalStrength_;
  }

  public static final int LATENCY_FIELD_NUMBER = 3;
  private float latency_ = 0F;
  /**
   * <code>float latency = 3;</code>
   * @return The latency.
   */
  @java.lang.Override
  public float getLatency() {
    return latency_;
  }

  public static final int THROUGHPUT_FIELD_NUMBER = 4;
  private float throughput_ = 0F;
  /**
   * <code>float throughput = 4;</code>
   * @return The throughput.
   */
  @java.lang.Override
  public float getThroughput() {
    return throughput_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (java.lang.Float.floatToRawIntBits(signalStrength_) != 0) {
      output.writeFloat(2, signalStrength_);
    }
    if (java.lang.Float.floatToRawIntBits(latency_) != 0) {
      output.writeFloat(3, latency_);
    }
    if (java.lang.Float.floatToRawIntBits(throughput_) != 0) {
      output.writeFloat(4, throughput_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (java.lang.Float.floatToRawIntBits(signalStrength_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, signalStrength_);
    }
    if (java.lang.Float.floatToRawIntBits(latency_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, latency_);
    }
    if (java.lang.Float.floatToRawIntBits(throughput_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, throughput_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof trainsim.proto.LTEData)) {
      return super.equals(obj);
    }
    trainsim.proto.LTEData other = (trainsim.proto.LTEData) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (java.lang.Float.floatToIntBits(getSignalStrength())
        != java.lang.Float.floatToIntBits(
            other.getSignalStrength())) return false;
    if (java.lang.Float.floatToIntBits(getLatency())
        != java.lang.Float.floatToIntBits(
            other.getLatency())) return false;
    if (java.lang.Float.floatToIntBits(getThroughput())
        != java.lang.Float.floatToIntBits(
            other.getThroughput())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + SIGNAL_STRENGTH_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSignalStrength());
    hash = (37 * hash) + LATENCY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLatency());
    hash = (37 * hash) + THROUGHPUT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getThroughput());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static trainsim.proto.LTEData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trainsim.proto.LTEData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trainsim.proto.LTEData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trainsim.proto.LTEData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trainsim.proto.LTEData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static trainsim.proto.LTEData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static trainsim.proto.LTEData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static trainsim.proto.LTEData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static trainsim.proto.LTEData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static trainsim.proto.LTEData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static trainsim.proto.LTEData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static trainsim.proto.LTEData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(trainsim.proto.LTEData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Encapsulates the LTEData we want to collect from NS3 to send to MCAPL
   * </pre>
   *
   * Protobuf type {@code trainsim.LTEData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trainsim.LTEData)
      trainsim.proto.LTEDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trainsim.proto.TrainSimProto.internal_static_trainsim_LTEData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trainsim.proto.TrainSimProto.internal_static_trainsim_LTEData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trainsim.proto.LTEData.class, trainsim.proto.LTEData.Builder.class);
    }

    // Construct using trainsim.proto.LTEData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      signalStrength_ = 0F;
      latency_ = 0F;
      throughput_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return trainsim.proto.TrainSimProto.internal_static_trainsim_LTEData_descriptor;
    }

    @java.lang.Override
    public trainsim.proto.LTEData getDefaultInstanceForType() {
      return trainsim.proto.LTEData.getDefaultInstance();
    }

    @java.lang.Override
    public trainsim.proto.LTEData build() {
      trainsim.proto.LTEData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public trainsim.proto.LTEData buildPartial() {
      trainsim.proto.LTEData result = new trainsim.proto.LTEData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(trainsim.proto.LTEData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.signalStrength_ = signalStrength_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.latency_ = latency_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.throughput_ = throughput_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof trainsim.proto.LTEData) {
        return mergeFrom((trainsim.proto.LTEData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(trainsim.proto.LTEData other) {
      if (other == trainsim.proto.LTEData.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSignalStrength() != 0F) {
        setSignalStrength(other.getSignalStrength());
      }
      if (other.getLatency() != 0F) {
        setLatency(other.getLatency());
      }
      if (other.getThroughput() != 0F) {
        setThroughput(other.getThroughput());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              signalStrength_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              latency_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              throughput_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private float signalStrength_ ;
    /**
     * <code>float signal_strength = 2;</code>
     * @return The signalStrength.
     */
    @java.lang.Override
    public float getSignalStrength() {
      return signalStrength_;
    }
    /**
     * <code>float signal_strength = 2;</code>
     * @param value The signalStrength to set.
     * @return This builder for chaining.
     */
    public Builder setSignalStrength(float value) {

      signalStrength_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float signal_strength = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignalStrength() {
      bitField0_ = (bitField0_ & ~0x00000002);
      signalStrength_ = 0F;
      onChanged();
      return this;
    }

    private float latency_ ;
    /**
     * <code>float latency = 3;</code>
     * @return The latency.
     */
    @java.lang.Override
    public float getLatency() {
      return latency_;
    }
    /**
     * <code>float latency = 3;</code>
     * @param value The latency to set.
     * @return This builder for chaining.
     */
    public Builder setLatency(float value) {

      latency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float latency = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatency() {
      bitField0_ = (bitField0_ & ~0x00000004);
      latency_ = 0F;
      onChanged();
      return this;
    }

    private float throughput_ ;
    /**
     * <code>float throughput = 4;</code>
     * @return The throughput.
     */
    @java.lang.Override
    public float getThroughput() {
      return throughput_;
    }
    /**
     * <code>float throughput = 4;</code>
     * @param value The throughput to set.
     * @return This builder for chaining.
     */
    public Builder setThroughput(float value) {

      throughput_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float throughput = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearThroughput() {
      bitField0_ = (bitField0_ & ~0x00000008);
      throughput_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trainsim.LTEData)
  }

  // @@protoc_insertion_point(class_scope:trainsim.LTEData)
  private static final trainsim.proto.LTEData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new trainsim.proto.LTEData();
  }

  public static trainsim.proto.LTEData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LTEData>
      PARSER = new com.google.protobuf.AbstractParser<LTEData>() {
    @java.lang.Override
    public LTEData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LTEData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LTEData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public trainsim.proto.LTEData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

