// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainsim.proto
// Protobuf Java Version: 4.29.3

package trainsim.proto;

public interface LTENodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trainsim.LTENode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The position a train node is currently at
   * </pre>
   *
   * <code>.trainsim.LTENode.Position position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <pre>
   * The position a train node is currently at
   * </pre>
   *
   * <code>.trainsim.LTENode.Position position = 2;</code>
   * @return The position.
   */
  trainsim.proto.LTENode.Position getPosition();
  /**
   * <pre>
   * The position a train node is currently at
   * </pre>
   *
   * <code>.trainsim.LTENode.Position position = 2;</code>
   */
  trainsim.proto.LTENode.PositionOrBuilder getPositionOrBuilder();
}
