// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainsim.proto
// Protobuf Java Version: 4.29.3

package trainsim.proto;

public final class TrainSimProto {
  private TrainSimProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TrainSimProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainsim_LTENode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_trainsim_LTENode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainsim_LTENode_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_trainsim_LTENode_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainsim_LTEData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_trainsim_LTEData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainsim_DataStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_trainsim_DataStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016trainsim.proto\022\010trainsim\032\033google/proto" +
      "buf/empty.proto\"e\n\007LTENode\022\n\n\002id\030\001 \001(\t\022," +
      "\n\010position\030\002 \001(\0132\032.trainsim.LTENode.Posi" +
      "tion\032 \n\010Position\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\"S" +
      "\n\007LTEData\022\n\n\002id\030\001 \001(\t\022\027\n\017signal_strength" +
      "\030\002 \001(\002\022\017\n\007latency\030\003 \001(\002\022\022\n\nthroughput\030\004 " +
      "\001(\002\".\n\nDataStatus\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t2\311\001\n\030VehicleLTEControlService" +
      "\0228\n\rinitTrainNode\022\021.trainsim.LTENode\032\024.t" +
      "rainsim.DataStatus\0222\n\ngetLTEData\022\021.train" +
      "sim.LTENode\032\021.trainsim.LTEData\022?\n\017startS" +
      "imulation\022\026.google.protobuf.Empty\032\024.trai" +
      "nsim.DataStatusB!\n\016trainsim.protoB\rTrain" +
      "SimProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_trainsim_LTENode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trainsim_LTENode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_trainsim_LTENode_descriptor,
        new java.lang.String[] { "Id", "Position", });
    internal_static_trainsim_LTENode_Position_descriptor =
      internal_static_trainsim_LTENode_descriptor.getNestedTypes().get(0);
    internal_static_trainsim_LTENode_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_trainsim_LTENode_Position_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_trainsim_LTEData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trainsim_LTEData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_trainsim_LTEData_descriptor,
        new java.lang.String[] { "Id", "SignalStrength", "Latency", "Throughput", });
    internal_static_trainsim_DataStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trainsim_DataStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_trainsim_DataStatus_descriptor,
        new java.lang.String[] { "Success", "Message", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
